### ISSUE TITLE
Clean up Branches

### ISSUE THREAD

**Issue by noeltock** [humanmade/hm-pattern-library#104]
Hey @mattheu @peterwilsoncc . With the redesign of the HM website coming along, I assume we'll want to find as much overlap as possible and get more mileage out of this pattern library.

There's a bunch of branches and I'm not sure if we'd be duplicating efforts with any alignment exercises (i.e. HM redesign styles making their way into this repo).

See here... anything that can be deleted/merged/etc?

![image](https://cloud.githubusercontent.com/assets/781166/24270546/b2842b7c-1069-11e7-8a34-ee73c821331a.png)

**Comment by mattheu** [comment]
👍 All gone.
