### ISSUE TITLE
HM logos appear to be broken

### ISSUE THREAD

**Issue by johnbillion** [humanmade/hm-pattern-library#122]
The [Brand Elements page](https://humanmade.github.io/hm-pattern-library/pages/brand.html) includes some HM logos which are broken and/or missing.

<img width="713" alt="screen shot 2017-05-22 at 00 22 50" src="https://cloud.githubusercontent.com/assets/208434/26288209/dabea4f2-3e84-11e7-8ce9-a74018b1bf82.png">

**Comment by mattheu** [comment]
I can't seem to reproduce this one. Are you using the branch V2-Redesign or the current release?

**Comment by mattheu** [comment]
Oh I see.. this is actually the version on the GH pages right now (the older version.) I don't see the logo missing. Can you give me some more info? EG is there something failing in the network tab?

**Comment by johnbillion** [comment]
Weird, it's fine today. Must have been a network issue.
