### ISSUE TITLE
Image references are wrong on external sites

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-pattern-library#25]
We've included the pattern library sass file in the handbook theme, but image references are relative to the `dist` folder of the handbook theme, while currently images are in `src`.

Do images perhaps need absolute references? Maybe external so the images aren't bundled at all?

**Comment by sambulance** [comment]
1. Standardise pattern library structure by adding an `assets` folder that will contain both `src` and `dist` folders
2. Set up a `!default` sass variable within the pattern library for the image path, which can then be overridden by themes that use a different structure

Images will be in `assets/src/images`

**Comment by peterwilsoncc** [comment]
@sambulance We could create a function for the image path so we have `background-image: hm-images( 'logo-alt-black.svg' );` that works similar to the way get_templagte_file() works in WP but it seems a little messy compared to an assets directory. 

What are your thougts?

**Comment by sambulance** [comment]
@peterwilsoncc As long as it can be overridden but a site that is using it, I'm happy with either solution.

The handbook theme is currently set up as `theme/assets/src/images`.

**Comment by mattheu** [comment]
Or just a variable that you can over-ride in the child theme
