### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-pattern-library#27]
Styling for default `get_search_form()` output

**Comment by mattheu** [comment]
Thought a bit about this - how about something like this?

![image](https://cloud.githubusercontent.com/assets/494927/16564215/2b31ecde-41fe-11e6-87f9-907ca3a527b8.png)

* Could have both light and dark version. 
* The icon could also function as a submit button.

Especially if we're doing live search, we have no need for a button. Also the button styles we have look pretty horrible on the red background... but if we can do without a button completely, thats something we can tackle when it arises!
