### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#34]
@sambulance Do we know the patterns we're going to use for the sidebar navigation on Handbook?

**Comment by sambulance** [comment]
Perhaps this could be a pattern in itself, as it will be an accordion style vertical nav - not something we have considered I think!

**Comment by sambulance** [comment]
Perhaps it can be reusable as an accordion style? Can them be used for FAQs etc?

**Comment by sambulance** [comment]
We kinda want it like twentyfifteen though, where stuff is clickable but also expandable: https://twentyfifteendemo.wordpress.com/

**Comment by mattheu** [comment]
We could use it for navigating all the components in the pattern library?

**Comment by mattheu** [comment]
And yeah something like 2015 would be perfect

**Comment by mattheu** [comment]
This is merged and meets our short term requirements for handbook. 

Will we want any other forms of navigation? eg Horizontal with dropdown?

**Comment by sambulance** [comment]
I doubt it for now - if it becomes something we need in future then we can build in

**Comment by mattheu** [comment]
In that case - lets close this issue for now.
