### ISSUE TITLE
Icons?

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#35]
I suspect we're going to want icons at some point.

I'd like to avoid adding an icon font - since we're not supporting IE8 we can just do pure SVG. 

Anyone got any ideas on this?

**Comment by peterwilsoncc** [comment]
https://icomoon.io/app/#/select will convert a font to SVGs and vice-versa

**Comment by mattheu** [comment]
Looks neat. Any suggestions on the set?

I like the look of the IcoMoon free set. Nice and simple. 

As long as it's not FontAwesome - I really don't like the design of the actual icons in this.

**Comment by mattheu** [comment]
For a couple of modules now - I've run into some requirements for icons. I've just included single icons from the iconmoon set.

This is a pretty simple way to do it and we could carry on like this - adding new icons as required.

Another idea - how about automating generating different color icons from SVG? Anybody done this before?

**Comment by sambulance** [comment]
I think that is how HM Icons works? https://github.com/humanmade/hm-icons

**Comment by mattheu** [comment]
You're right - `hm-icons` does do this - but also does a whole bunch more. Also is a WP/PHP dependency which I'd like to avoid. And I think a lot of the complexity is to support IE8 which we're not bothered about.

I took a look though and it does just do this: 

```$svg = str_replace( '<path ', "<path fill=\"#{$colour}\" ", $svg );```

We could probably do something similar in a gulp build task so we only need black svg files in src, and auto generate the colour variations as part of the build task.

**Comment by sambulance** [comment]
Yeah I didn't mean as a dependency, just as a reference on how they generate the SVG. Pretty sure there will be a gulp task for that! We probably just need to make sure our SVG paths are labelled so they can be targeted?

**Comment by mattheu** [comment]
👍

**Comment by mattheu** [comment]
Fixed by https://github.com/humanmade/hm-pattern-library/pull/108

**Comment by mattheu** [comment]
I'm going to close this one. We've had icons for ages :D
