### ISSUE TITLE
Extra spacing from file include

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#37]
Our file include script is adding an extra space between included files.

I think its a unicode character. I suspect this is the issue: https://github.com/coderhaoxin/gulp-file-include/issues/102

However.. not sure how to fix. I tried some of the things suggested, as well as trying to use a filter along with the stripBom gulp task.

Maybe theres a better gulp task we could use.

**Comment by libby-barker** [comment]
@mattheu is there someone familiar with Gulp we could assign this to?

**Comment by mattheu** [comment]
Ummmm me maybe? :) But I'm happy to leave unassigned in case someone jumps in and has some ideas!

TBH - Its not a priority. I quite like the extra spacing between modules. But ideally we'd fix this but and style properly.

**Comment by mattheu** [comment]
Woop. Fixed in https://github.com/humanmade/hm-pattern-library/pull/67

Had to do a search/replace for the spacing that got added after we did the fileinclude.
