### ISSUE TITLE
JS Dependencies - jQuery

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#47]
@sambulance raised an interesting point over on https://github.com/humanmade/hm-pattern-library/pull/44. Do we depend on jQuery? I felt like this was a bigger discussion - don't want to derail that ticket.

My initial reaction was that I agreed. It's probably overkill for this single component. 

However I'm not 100% convinced. Other components may not be so easy to write without it. Furthermore, writing it can be a little frustrating to work around some of the issues and is possibly a little less readable/maintainable. Also jQuery handles some browser compatibility (eg using `classList` is IE10+)

On the one hand I'm keen to keep jQuery out of the pattern library itself. We may well want to use it independently of WP where jQuery isn't so ubiquitous and its nice to keep it really lean.

On the other, it's less than 40kb, and can be mroe readable, plus has some performance/compatability advantages. When we're loading 400kb of fonts it doesn't seem so bad.

If we drop it - what are the alternatives
- [Zepto.js](http://zeptojs.com/) - a lighter weight (> 10kb) jQuery compatible lib. However [zurb foundation backed out of using it](http://zeptojs.com/) because it's not really compatible enough. Also they claim it isn't as performant as jQuery once loaded.
- Something like ES2015 provides a bunch of methods that ease the frustration at not having jQuery. But would require a bunch of build tools to turn this into functional, browser compatible code.
- jQuery - If you're not relying on the version bundled with WP you can build a custom version removing some unused modules to slim it down.

Right now, I think we still have a small enough amount of JS to do away with the jQuery dependency. But we ultimately need to ship stuff, and I don't want this to become a barrier for the sake of 40kb.

I'm pretty on the fence about this one, and would love to have some feedback.

**Comment by peterwilsoncc** [comment]
The biggest issue with WP's bundled jQuery is the two blocking requests it adds to the HTML header. If we can avoid it, lets. 

Another alternative is https://github.com/filamentgroup/shoestring, it's a subset of the jQuery API so we can use the following code to pretend:

```js
( function( window, $ ) {
} ( window, shoestring ) );
```

The 400K of fonts is a good point, although they can be set to load async so the blocking doesn't apply.

**Comment by sambulance** [comment]
I think for the little amount of JS we have, it's worth spending a bit of extra time writing vanilla JS. I wouldn't worry too much about browsers support, I think we already agreed that we won't be supporting legacy browsers.

**Comment by mattheu** [comment]
Agreed. I also think it's reasonable to support IE10+ for this project.

If we end up with complex components down the line, they could be built as 'plugins' that are loaded separately and can have a jQuery/Shoestring dependency - but are not loaded by default for all. The core JS should be kept as lean as possible.

**Comment by mattheu** [comment]
I'm going to close this ticket - great to get your thoughts on this!
