### ISSUE TITLE
Accordion nav - active/current indicator

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#52]
Currently we just underline - but would be nice to have something more obvious, and nicer looking.

![image](https://cloud.githubusercontent.com/assets/494927/16618513/baedbbee-4381-11e6-89dc-5e2a07ccb788.png)

**Comment by sambulance** [comment]
The accordion nav was removed in https://github.com/humanmade/hm-pattern-library/issues/124
