### ISSUE TITLE
Create release branch

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-pattern-library#56]
Related issue from the handbook: https://github.com/humanmade/hm-handbook-theme/issues/21

> In order to load app.js, it requires the compiled pattern library, which isn't available unless you do it manually in the submodule. Perhaps we should maybe look at doing a 'release' branch that consists only of the dist directory? In fact... is this the same as the gh-pages branch?

**Comment by mattheu** [comment]
Also related https://github.com/humanmade/hm-pattern-library/pull/54.

Frustratingly, I think the github pages (gh-pages) branch and the release branch would be the same. But we can't change which branch is used for github pages.

- We could have 2 identical branches 
- We could document that the 'release' branch is the 'gh-pages' branch 
- You can do tag releases that allow you to attach a zip of the built release. (Neat but not so useful for submodules)

**Comment by mattheu** [comment]
We've got the `gh-pages` branch - which is essentially a release branch. Plus we have tagged releases that will show up here https://github.com/humanmade/hm-pattern-library/releases

I think thats good enough - i'd be happy to close this. Any thoughts?

**Comment by mattheu** [comment]
I'm going to close. I'm happy with tagged releases and the `gh-pages` branch. Do reopen/comment if you disagree with me!
