### ISSUE TITLE
Accordion nav - line height

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-pattern-library#62]
Reduce the line height of single items, at the moment there's a fair gap between lines. Eg. "Remote work" and "allowance"

![screen shot 2016-07-11 at 15 27 41](https://cloud.githubusercontent.com/assets/5014023/16851227/7e3a909e-49fa-11e6-9f97-eb9ca0829d49.jpg)

**Comment by mattheu** [comment]
👍

**Comment by willmot** [comment]
I guess sub-pages of the current page shouldn't be underlined also?

Also, when on a page with children, should the menu be auto-expanded to show the children?

**Comment by willmot** [comment]
Ah just seen https://github.com/humanmade/hm-pattern-library/pull/61

**Comment by mattheu** [comment]
This is fixed
