### ISSUE TITLE
Table thead and tbody

### ISSUE THREAD

**Issue by pdewouters** [humanmade/hm-pattern-library#68]
Would be useful to add a header row style for `<thead><th></th></thead>`

**Comment by mattheu** [comment]
And caption?

**Comment by pdewouters** [comment]
<img width="281" alt="screenshot 2016-07-22 17 03 38" src="https://cloud.githubusercontent.com/assets/30460/17063267/4d13c7d0-502e-11e6-862b-e19bd659679c.png">
<img width="780" alt="screenshot 2016-07-22 17 03 32" src="https://cloud.githubusercontent.com/assets/30460/17063268/4d28c9fa-502e-11e6-8446-38a280c2eb82.png">

**Comment by mattheu** [comment]
Looks great. Reckon they should have a border bottom too?

**Comment by pdewouters** [comment]
yeah sorry, that's why I posted it, forgot to add comment.

**Comment by mattheu** [comment]
Done!
