### ISSUE TITLE
Blue for primary button

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#76]
Whilst building the handbook site, it seemed like the blue 'secondary' button had more weight to it than the red primary button, as we're using red so extensively - eg the header + link color etc.

I propose switching the 'Primary' button to be blue and keep red as secondary.

**Comment by missjwo** [comment]
if you have the red and bleu next to each other, the read seems more dominate as the primary colour and you wouldnt want to change the primary button colour depending on whether there was more than one button. :/

**Comment by mattheu** [comment]
I think that's why we made red primary. But just thinking about what if everything else is red too 😀

**Comment by missjwo** [comment]
Do we have an example of where the differebces are shown? Maybe seeing it in a example would help opinions solidify.  

--  

Jenny

**Comment by mattheu** [comment]
![image](https://cloud.githubusercontent.com/assets/494927/17618494/10ec8f76-6078-11e6-921b-7530ebe8fac7.png)

**Comment by mattheu** [comment]
One suggestion (from @noeltock I believe, but can't find the source) we had was to use a subtle text shadow to improve the contrast. 

I'm still mixed on this one, as the design is very flat and shadows go against this.

**Comment by mattheu** [comment]
No longer an issue with the V2 redesign.
