### ISSUE TITLE
EPIC: 2.0 HM Redesign

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-pattern-library#98]
Bring the pattern library in line with the new HMN.MD website following the redesign.

**Comment by joemcgill** [comment]
@mattheu as work is happening on the redesign, should we be pushing changes back to the `v2-release` branch or did you have something else in mind?

**Comment by mattheu** [comment]
I think just push all changes to the V2 redesign branch. If you want me to review changes as you go along, open pull requests against this branch. But it could make the workflow complex, so we could just do a review on all the changes when we're done? I don't think anywone has reviewed my changes made on the V2-Redesign branch yet.

**Comment by joemcgill** [comment]
Thanks @mattheu. I may do PRs on any big changes along the way in order to keep from having a bunch of cleanup/rework at the end, but generally I think a "review at the end" strategy sounds good.

**Comment by mattheu** [comment]
YEah - sometimes when you're working on a feature, you need to do some quick iterations, and the review process can slow things down. So feature branch with review at the end makes things quicker.
